apiVersion: v1
entries:
  stunner-neko:
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2024-09-06T15:51:46.77747984+02:00"
    dependencies:
    - condition: stunner.install
      name: stunner-gateway-operator
      repository: https://l7mp.io/stunner
      version: 0.19.0
    description: A Helm chart for Kubernetes
    digest: 8ace9c11b843b215c7c0066fe3b10b3c25884c714159792a5a79493252bddf58
    name: stunner-neko
    type: application
    urls:
    - https://lukacsi.github.io/helm-charts/charts/stunner-neko-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2024-09-06T15:51:46.759610539+02:00"
    dependencies:
    - condition: stunner.install
      name: stunner-gateway-operator
      repository: https://l7mp.io/stunner
      version: 0.19.0
    description: A Helm chart for Kubernetes
    digest: eade7f0bd24c0a715993b377233ffedda96095d01ed84b70d546e7238a566ac1
    name: stunner-neko
    type: application
    urls:
    - https://lukacsi.github.io/helm-charts/charts/stunner-neko-0.1.0.tgz
    version: 0.1.0
generated: "2024-09-06T15:51:46.750335969+02:00"
