{{- if .Values.ipset }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.roles.configMapUpdater.name }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update", "delete", "list", "watch", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.roles.serviceViewer.name }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list", "get", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.roles.deploymentViewer.name }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roles.configMapUpdater.name }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
roleRef:
  kind: Role
  name: {{ .Values.roles.configMapUpdater.name }}
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roles.serviceViewer.name }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
roleRef:
  kind: Role
  name: {{ .Values.roles.serviceViewer.name }}
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roles.deploymentViewer.name }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
roleRef:
  kind: Role
  name: {{ .Values.roles.deploymentViewer.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}